id: P003023
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG24729
  title: འབྲི་གུང་རྒྱུད་བཞིའི་དཀའ་མཆན།
  author: ''
  volumes:
    dfda8f1c495b45cebc8adb1ff2f06938:
      image_group_id: I1KG24731
      title: ''
      volume_number: 1
      total_pages: 995
      base_file: v001.txt
