id: P003023
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 10:34:56.283068
source_metadata:
  id: bdr:W1KG24729
  title: འབྲི་གུང་རྒྱུད་བཞིའི་དཀའ་མཆན།
  author: ''
  volumes:
    dfda8f1c495b45cebc8adb1ff2f06938:
      image_group_id: I1KG24731
      title: ''
      volume_number: 1
      total_pages: 995
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
